//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stokEntities : DbContext
    {
        public stokEntities()
            : base("name=stokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<depo> depo { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<StkDurum> StkDurum { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<StkHareket> StkHareket { get; set; }
    }
}
