//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip2
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.StkDurum = new HashSet<StkDurum>();
            this.StkHareket = new HashSet<StkHareket>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<System.DateTime> product_date { get; set; }
        public string product_detail { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
        public string olcu_birimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StkDurum> StkDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StkHareket> StkHareket { get; set; }
    }
}
