//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StkDurum
    {
        public int durum_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> depo_id { get; set; }
        public Nullable<int> stk_miktar { get; set; }
    
        public virtual depo depo { get; set; }
        public virtual product product { get; set; }
    }
}
