//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StkHareket
    {
        public int hareket_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> depo_id { get; set; }
        public Nullable<int> stk_miktar { get; set; }
        public string stk_olcu { get; set; }
        public string hareket_turu { get; set; }
        public Nullable<System.DateTime> hareket_tarih { get; set; }
        public string user_name { get; set; }
    
        public virtual depo depo { get; set; }
        public virtual product product { get; set; }
    }
}
