//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip2
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int users_id { get; set; }
        public string users_fname { get; set; }
        public string users_lname { get; set; }
        public string users_mail { get; set; }
        public string users_type { get; set; }
        public Nullable<System.DateTime> u_tarih { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> degistirme_tarihi { get; set; }
    }
}
